In [1]:
# import pandas library

import pandas as pd

In [2]:
# load dataset

dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
# Categorical input data
# Nominal - one hot encoding

dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
#split input data

independent=dataset[['age', 'bmi', 'children',  'sex_male','smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [5]:
# split output data

dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [6]:
# Split training and testing data

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [7]:
# Standardization

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [10]:
# GridSearchCV Model Creation - Decision Tree

# criterion{“squared_error”, “friedman_mse”, “absolute_error”, “poisson”}, default=”squared_error”
# splitter{“best”, “random”}, default=”best”
# max_featuresint, float or {“auto”, “sqrt”, “log2”}, default=None

from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

param_grid= { 'criterion':['squared_error', 'friedman_mse', 'absolute_error','poisson'],
               'splitter':['best','random'],
            'max_features':['auto', 'sqrt','log2']}

grid=GridSearchCV(DecisionTreeRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)

grid.fit(x_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

F:\Anaconda\Lib\site-packages\sklearn\tree\_classes.py:277: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0'`.
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [14]:
#Print hyper tuning parameter and r2_score

result=grid.cv_results_

# Evaluation Metrics

y_pred=grid.predict(x_test)

# r2_score

from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
print("The r2_score with hyper tuning parameter {}".format(grid.best_params_),r_score)

The r2_score with hyper tuning parameter {'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'best'} 0.6959287354824849

In [16]:
# view in table format

table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.072450,0.028151,0.007864,0.003956,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",0.743249,0.538869,0.761895,0.644926,0.679458,0.673679,0.079569,2
1,0.022384,0.004077,0.009396,0.002496,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",0.689811,0.574291,0.715379,0.637421,0.610433,0.645467,0.051405,7
2,0.018188,0.003708,0.007795,0.000979,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.724092,0.566608,0.742570,0.460592,0.609691,0.620710,0.104138,14
3,0.016989,0.002279,0.009594,0.002869,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.686899,0.588631,0.634375,0.417167,0.625865,0.590587,0.092213,19
4,0.020187,0.002992,0.008595,0.001200,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.714473,0.536930,0.676795,0.566908,0.685623,0.636146,0.070531,9
5,0.016589,0.002497,0.016590,0.008471,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.750755,0.632041,0.595905,0.446955,0.597060,0.604543,0.097055,18
6,0.037176,0.006760,0.009595,0.002726,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.751913,0.562764,0.784073,0.621522,0.668368,0.677728,0.081580,1
7,0.029182,0.003865,0.019988,0.009731,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.560360,0.600597,0.568990,0.709646,0.657323,0.619383,0.056503,15
8,0.023784,0.001720,0.012594,0.002937,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.764627,0.601906,0.676550,0.622076,0.650915,0.663215,0.056683,3
9,0.022783,0.003428,0.012394,0.001854,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.721174,0.596159,0.630603,0.447648,0.555454,0.590208,0.089834,20
10,0.021610,0.007404,0.012592,0.005672,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.712638,0.574774,0.681977,0.630437,0.488007,0.617567,0.079962,16
11,0.018014,0.007326,0.009004,0.005499,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.622439,0.553668,0.721112,0.274655,0.527829,0.539941,0.148553,24
12,0.111700,0.009275,0.007051,0.002690,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",0.733846,0.624338,0.592911,0.498936,0.677282,0.625463,0.079375,12
13,0.086988,0.004351,0.007638,0.006710,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",0.661308,0.678749,0.625438,0.643013,0.607610,0.643224,0.025195,8
14,0.062515,0.011065,0.009665,0.000810,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.701911,0.616219,0.505202,0.631977,0.626726,0.616407,0.063287,17
15,0.050196,0.012135,0.006829,0.005158,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.772933,0.515552,0.739350,0.566914,0.546681,0.628286,0.106200,11
16,0.063059,0.009526,0.009456,0.000847,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.756196,0.568577,0.674078,0.549704,0.681523,0.646016,0.076760,5
17,0.050078,0.003771,0.006845,0.003683,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.355224,0.662983,0.625449,0.676609,0.593403,0.582734,0.117432,22
18,0.114623,0.149911,0.004856,0.004344,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",0.699270,0.576799,0.686326,0.573985,0.625108,0.632297,0.052795,10
19,0.019814,0.000828,0.008498,0.003229,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",0.704207,0.678444,0.597402,0.621497,0.656513,0.651613,0.038356,4
20,0.064273,0.084109,0.008506,0.003231,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.688312,0.623101,0.672553,0.597545,0.647538,0.645810,0.032771,6
21,0.043644,0.055084,0.004863,0.003516,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.711162,0.602093,0.514433,0.431567,0.625023,0.576856,0.095917,23
22,0.018208,0.003130,0.007698,0.003928,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.649454,0.725132,0.512794,0.665704,0.555572,0.621731,0.076991,13
23,0.014959,0.003953,0.005270,0.003951,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.686597,0.548148,0.440364,0.652899,0.611306,0.587863,0.087018,21

In [17]:
#Output

age=float(input("Age :"))
bmi=float(input("BMI :"))
children=int(input("Children :"))
sex_male=int(input("Sex_male 1 or 0 :"))
smoker_yes=int(input("Smoker 1 0r 0 :"))

Age :12
BMI :23
Children :3
Sex_male 1 or 0 :1
Smoker 1 0r 0 :1

In [19]:
#Output Prediction

Prediction=grid.predict([[age,bmi,children,sex_male,smoker_yes]])
print("Future Prediction {}".format(Prediction))

Future Prediction [63770.42801]