In [1]:
#import pandas library

import pandas as pd

In [2]:
#load dataset

dataset=pd.read_csv("50_Startups.csv")
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [3]:
# Categorical input data

dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156991.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.95,311613.29,152211.77,0,1
9,123334.88,108679.17,304981.62,149759.96,0,0
10,101913.08,110594.11,229160.95,146121.95,1,0
11,100671.96,91790.61,249744.55,144259.40,0,0
12,93863.75,127320.38,249839.44,141585.52,1,0
13,91992.39,135495.07,252664.93,134307.35,0,0
14,119943.24,156547.42,256512.92,132602.65,1,0
15,114523.61,122616.84,261776.23,129917.04,0,1
16,78013.11,121597.55,264346.06,126992.93,0,0
17,94657.16,145077.58,282574.31,125370.37,0,1
18,91749.16,114175.79,294919.57,124266.90,1,0
19,86419.70,153514.11,0.00,122776.86,0,1
20,76253.86,113867.30,298664.47,118474.03,0,0
21,78389.47,153773.43,299737.29,111313.02,0,1
22,73994.56,122782.75,303319.26,110352.25,1,0
23,67532.53,105751.03,304768.73,108733.99,1,0
24,77044.01,99281.34,140574.81,108552.04,0,1
25,64664.71,139553.16,137962.62,107404.34,0,0
26,75328.87,144135.98,134050.07,105733.54,1,0
27,72107.60,127864.55,353183.81,105008.31,0,1
28,66051.52,182645.56,118148.20,103282.38,1,0
29,65605.48,153032.06,107138.38,101004.64,0,1
30,61994.48,115641.28,91131.24,99937.59,1,0
31,61136.38,152701.92,88218.23,97483.56,0,1
32,63408.86,129219.61,46085.25,97427.84,0,0
33,55493.95,103057.49,214634.81,96778.92,1,0
34,46426.07,157693.92,210797.67,96712.80,0,0
35,46014.02,85047.44,205517.64,96479.51,0,1
36,28663.76,127056.21,201126.82,90708.19,1,0
37,44069.95,51283.14,197029.42,89949.14,0,0
38,20229.59,65947.93,185265.10,81229.06,0,1
39,38558.51,82982.09,174999.30,81005.76,0,0
40,28754.33,118546.05,172795.67,78239.91,0,0
41,27892.92,84710.77,164470.71,77798.83,1,0
42,23640.93,96189.63,148001.11,71498.49,0,0
43,15505.73,127382.30,35534.17,69758.98,0,1
44,22177.74,154806.14,28334.72,65200.33,0,0
45,1000.23,124153.04,1903.93,64926.08,0,1
46,1315.46,115816.21,297114.46,49490.75,1,0
47,0.00,135426.92,0.00,42559.73,0,0
48,542.05,51743.15,0.00,35673.41,0,1
49,0.00,116983.80,45173.06,14681.40,0,0

In [5]:
# view dataset column names

dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [4]:
# split input data

independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend', 
       'State_Florida', 'State_New York']]
independent

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.20       136897.80        471784.10              0               1
1   162597.70       151377.59        443898.53              0               0
2   153441.51       101145.55        407934.54              1               0
3   144372.41       118671.85        383199.62              0               1
4   142107.34        91391.77        366168.42              1               0
5   131876.90        99814.71        362861.36              0               1
6   134615.46       147198.87        127716.82              0               0
7   130298.13       145530.06        323876.68              1               0
8   120542.52       148718.95        311613.29              0               1
9   123334.88       108679.17        304981.62              0               0
10  101913.08       110594.11        229160.95              1               0
11  100671.96        91790.61        249744.55              0               0
12   93863.75       127320.38        249839.44              1               0
13   91992.39       135495.07        252664.93              0               0
14  119943.24       156547.42        256512.92              1               0
15  114523.61       122616.84        261776.23              0               1
16   78013.11       121597.55        264346.06              0               0
17   94657.16       145077.58        282574.31              0               1
18   91749.16       114175.79        294919.57              1               0
19   86419.70       153514.11             0.00              0               1
20   76253.86       113867.30        298664.47              0               0
21   78389.47       153773.43        299737.29              0               1
22   73994.56       122782.75        303319.26              1               0
23   67532.53       105751.03        304768.73              1               0
24   77044.01        99281.34        140574.81              0               1
25   64664.71       139553.16        137962.62              0               0
26   75328.87       144135.98        134050.07              1               0
27   72107.60       127864.55        353183.81              0               1
28   66051.52       182645.56        118148.20              1               0
29   65605.48       153032.06        107138.38              0               1
30   61994.48       115641.28         91131.24              1               0
31   61136.38       152701.92         88218.23              0               1
32   63408.86       129219.61         46085.25              0               0
33   55493.95       103057.49        214634.81              1               0
34   46426.07       157693.92        210797.67              0               0
35   46014.02        85047.44        205517.64              0               1
36   28663.76       127056.21        201126.82              1               0
37   44069.95        51283.14        197029.42              0               0
38   20229.59        65947.93        185265.10              0               1
39   38558.51        82982.09        174999.30              0               0
40   28754.33       118546.05        172795.67              0               0
41   27892.92        84710.77        164470.71              1               0
42   23640.93        96189.63        148001.11              0               0
43   15505.73       127382.30         35534.17              0               1
44   22177.74       154806.14         28334.72              0               0
45    1000.23       124153.04          1903.93              0               1
46    1315.46       115816.21        297114.46              1               0
47       0.00       135426.92             0.00              0               0
48     542.05        51743.15             0.00              0               1
49       0.00       116983.80         45173.06              0               0

In [5]:
# split output data

dependent=dataset[['Profit']]
dependent

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [7]:
# GridSearchCVModel Creation - Random Forest

# n_estimators:int, default=100
# max_features{“sqrt”, “log2”, None}, int or float, default=1.0
# criterion{“squared_error”, “absolute_error”, “friedman_mse”, “poisson”}, default=”squared_error”

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid ={'criterion':['squared_error', 'friedman_mse','absolute_error','poisson'], 
              'max_features':['sqrt','log2',None],
              'n_estimators':[100,200]}

grid=GridSearchCV(RandomForestRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)

grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

F:\Anaconda\Lib\site-packages\sklearn\model_selection\_search.py:909: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2', None],
                         'n_estimators': [100, 200]},
             verbose=3)

In [11]:
#Print r2_score with hyper tuning parameter

result=grid.cv_results_

print("The r2_score with hyper tuning parameter {}".format(grid.best_params_))

The r2_score with hyper tuning parameter {'criterion': 'poisson', 'max_features': None, 'n_estimators': 100}

In [12]:
# View in table format

table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.536972,0.042059,0.111451,0.024206,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",-7.537381,-6.344046,-7.413649,-1.144418,-3.991588,-5.286217,2.430772,11
1,2.995038,0.077244,0.194176,0.026172,squared_error,sqrt,200,"{'criterion': 'squared_error', 'max_features':...",-8.113920,-6.844222,-9.686132,-0.829149,-4.228893,-5.940463,3.118517,22
2,1.608291,0.063981,0.123377,0.017501,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",-7.931458,-7.269198,-8.915720,-1.448975,-4.227285,-5.958527,2.745490,23
3,3.250420,0.328868,0.215586,0.057134,squared_error,log2,200,"{'criterion': 'squared_error', 'max_features':...",-7.394201,-7.374606,-7.588304,-1.475994,-4.071371,-5.580895,2.435736,14
4,2.179408,0.245952,0.163755,0.033746,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",-5.434030,-3.317816,-7.570180,-1.799452,-2.284637,-4.081223,2.145689,4
5,4.201947,0.426378,0.178119,0.007653,squared_error,None,200,"{'criterion': 'squared_error', 'max_features':...",-5.274623,-3.391223,-7.871262,-1.937847,-2.341665,-4.163324,2.184084,6
6,1.739575,0.129521,0.112195,0.014755,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",-7.645233,-7.562384,-7.620078,-1.554320,-4.062426,-5.688888,2.482209,16
7,3.427402,0.077905,0.237182,0.036340,friedman_mse,sqrt,200,"{'criterion': 'friedman_mse', 'max_features': ...",-7.544626,-7.298179,-8.729140,-0.974982,-4.326258,-5.774637,2.804197,19
8,1.723930,0.111031,0.130973,0.012306,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",-7.455728,-7.690260,-8.527494,-1.167085,-4.059077,-5.779929,2.765735,20
9,3.261312,0.153945,0.187493,0.039527,friedman_mse,log2,200,"{'criterion': 'friedman_mse', 'max_features': ...",-7.069598,-7.866231,-8.746070,-1.330635,-3.852470,-5.773001,2.768573,18
10,1.811026,0.103193,0.118745,0.023384,friedman_mse,None,100,"{'criterion': 'friedman_mse', 'max_features': ...",-5.915836,-2.989946,-6.914637,-1.711674,-2.117794,-3.929977,2.094773,2
11,4.251783,0.103178,0.264118,0.049581,friedman_mse,None,200,"{'criterion': 'friedman_mse', 'max_features': ...",-5.562695,-3.265473,-7.719496,-2.143760,-2.240575,-4.186400,2.153308,7
12,2.132762,0.076833,0.149979,0.040236,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",-7.526084,-6.906049,-6.433327,-1.205465,-4.348201,-5.283825,2.301700,10
13,3.987065,0.177228,0.220294,0.037094,absolute_error,sqrt,200,"{'criterion': 'absolute_error', 'max_features'...",-7.385939,-7.278957,-5.486202,-0.881205,-4.055135,-5.017488,2.407424,9
14,2.227460,0.307046,0.140780,0.033045,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",-7.566607,-7.483241,-7.758389,-0.441126,-4.119106,-5.473694,2.856573,13
15,4.381737,0.208829,0.212018,0.029897,absolute_error,log2,200,"{'criterion': 'absolute_error', 'max_features'...",-7.418313,-7.719376,-6.742424,-1.472320,-3.847162,-5.439919,2.411854,12
16,2.163987,0.087562,0.101201,0.019988,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",-5.764232,-3.345634,-6.716321,-2.175589,-2.169592,-4.034274,1.875745,3
17,3.881810,0.168168,0.187265,0.032872,absolute_error,None,200,"{'criterion': 'absolute_error', 'max_features'...",-5.625503,-3.373545,-7.584615,-1.965596,-2.225254,-4.154903,2.147218,5
18,1.628574,0.045602,0.115904,0.022325,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",-7.548550,-7.216072,-7.510579,-2.267047,-3.667274,-5.641904,2.231326,15
19,3.368765,0.136885,0.213238,0.035802,poisson,sqrt,200,"{'criterion': 'poisson', 'max_features': 'sqrt...",-7.515512,-7.617888,-8.704945,-1.994211,-4.068887,-5.980289,2.530007,24
20,1.728695,0.131331,0.118127,0.004397,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",-7.928602,-8.196324,-7.132295,-1.402861,-4.287243,-5.789465,2.595035,21
21,3.531344,0.205401,0.227614,0.029412,poisson,log2,200,"{'criterion': 'poisson', 'max_features': 'log2...",-7.961792,-7.455182,-6.797188,-2.248642,-4.104594,-5.713479,2.184329,17
22,2.131197,0.075422,0.127621,0.037071,poisson,None,100,"{'criterion': 'poisson', 'max_features': None,...",-5.723785,-3.156530,-5.844777,-2.299163,-2.344527,-3.873756,1.589958,1
23,3.334601,0.439915,0.167897,0.013152,poisson,None,200,"{'criterion': 'poisson', 'max_features': None,...",-5.535667,-3.132914,-8.040150,-2.413163,-2.156796,-4.255738,2.237023,8

In [13]:
#Output from EndUser

rd_spend=float(input("R & D Spend :"))
administration=float(input("Administration :"))
marketing_spend=float(input("Marketing Spend :"))
state_florida=int(input("State_Florida 1 0r 0:"))
state_newyork=int(input("State_NewYork 1 0r 0 :"))


#Output Prediction

Prediction=grid.predict([[rd_spend, administration, marketing_spend, state_florida, state_newyork]])
print("Future Prediction {} ".format(Prediction))

R & D Spend :10000
Administration :10000
Marketing Spend :10000
State_Florida 1 0r 0:1
State_NewYork 1 0r 0 :0
Future Prediction [63499.8628]

F:\Anaconda\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(